name: Build

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version:
        - '17'
        - '26'

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java-version }}
        cache: maven

    - name: Verify build
      run: mvn --batch-mode clean install spotless:check
