name: Build

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build:
        - name: "Java 17 (LTS) without JSpecify"
          java: 17
          profiles: "!jspecify"
        - name: "Java 25 (LTS) with JSpecify"
          java: 25
          profiles: ""
        - name: "Java 26 (latest) with JSpecify"
          java: 26
          profiles: ""

    name: ${{ matrix.build.name }}

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Setup JDK ${{ matrix.build.java }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.build.java }}
        cache: maven

    - name: Build
      run: |
        mvn --batch-mode \
          ${{ matrix.build.profiles && format('-P {0}', matrix.build.profiles) }} \
          clean install spotless:check
