name: Fix Flaky

on: [push, pull_request]

jobs:

  run_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Run Test
        run: mvn -pl typescript-generator-core test -Dtest="cz.habarta.typescript.generator.TaggedUnionsTest#testTaggedUnionsWithInterfaces"
                
  run_test_with_nondex:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
        
    - name: Run Test w nondex
      run: mvn -pl typescript-generator-core nondex:debug -Dtest='cz.habarta.typescript.generator.TaggedUnionsTest#testTaggedUnionsWithInterfaces'
